In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#Define vocabulary size
voc_size = 10000 

In [5]:
#One Hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7844, 2025, 534, 4028],
 [7844, 2025, 534, 4627],
 [7844, 4449, 534, 4943],
 [2292, 4583, 4797, 1655, 1309],
 [2292, 4583, 4797, 1655, 827],
 [5928, 7844, 8629, 534, 2022],
 [180, 9188, 1044, 1655]]

In [6]:
#Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7844 2025  534 4028]
 [   0    0    0    0 7844 2025  534 4627]
 [   0    0    0    0 7844 4449  534 4943]
 [   0    0    0 2292 4583 4797 1655 1309]
 [   0    0    0 2292 4583 4797 1655  827]
 [   0    0    0 5928 7844 8629  534 2022]
 [   0    0    0    0  180 9188 1044 1655]]


In [9]:
#feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\DS Projects\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 324ms/step


array([[[ 0.01039586, -0.03309204,  0.02886366,  0.03107358,
         -0.0053534 ,  0.010665  , -0.0373732 , -0.04609934,
         -0.04681037,  0.04750377],
        [ 0.01039586, -0.03309204,  0.02886366,  0.03107358,
         -0.0053534 ,  0.010665  , -0.0373732 , -0.04609934,
         -0.04681037,  0.04750377],
        [ 0.01039586, -0.03309204,  0.02886366,  0.03107358,
         -0.0053534 ,  0.010665  , -0.0373732 , -0.04609934,
         -0.04681037,  0.04750377],
        [ 0.01039586, -0.03309204,  0.02886366,  0.03107358,
         -0.0053534 ,  0.010665  , -0.0373732 , -0.04609934,
         -0.04681037,  0.04750377],
        [-0.03454505, -0.00370929, -0.02860541, -0.02031087,
         -0.00227283, -0.03540254, -0.04414044, -0.02149227,
          0.00704881, -0.04428412],
        [-0.04816661, -0.04703936, -0.03531622, -0.0050338 ,
          0.00246913,  0.04619693, -0.0061428 ,  0.02336494,
         -0.0313453 ,  0.04023453],
        [-0.03551067, -0.00366985, -0.01045554, -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 7844, 2025,  534, 4028])